import {validate,plan} from './planner.mjs';
import {parseSettings} from './settings.mjs';
const $=id=>document.getElementById(id);let data,current,steps=[],index=0,remaining=0,deadline=0,running=false,active=false,elapsed=0,last=0,audio,started,completed=false;
const fmt=s=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.ceil(s%60).toString().padStart(2,'0')}`;
function beep(){try{if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);g.gain.value=.08;o.frequency.value=660;o.start();o.stop(audio.currentTime+.15);}catch{}}
function show(id){for(const s of ['setup','player','finish'])$(s).hidden=s!==id;}
function refresh(){try{current=plan(data,{day:Number($('day').value),minutes:Number($('duration').value),energy:$('energy').value,knee:$('knee').value,run:$('run').value});$('title').textContent=current.title;$('summary').textContent=current.steps.length?`${$('duration').value} minutes · Échauffement et pauses inclus · Deux haltères de 5 kg si adaptés`:'Jour de repos';$('notice').textContent=current.notice;$('start').disabled=!current.steps.length;$('preview').replaceChildren(...[...new Set(current.steps.filter(s=>s.phase==='Exercice').map(s=>s.name))].map(name=>{const li=document.createElement('li');li.textContent=name;return li;}));}catch(e){$('error').textContent=e.message;$('start').disabled=true;}}
function render(){const s=steps[index];$('phase').textContent=`${s.phase} · Étape ${index+1} / ${steps.length}`;$('exercise').textContent=s.name;$('cue').textContent=s.cue;$('target').textContent=s.target||'À ton rythme';$('clock').textContent=fmt(Math.ceil(remaining));$('next').textContent=steps[index+1]?`Ensuite : ${steps[index+1].name} · ${steps[index+1].phase}`:'Dernière étape';$('progress').value=100*(index/steps.length);$('pause').textContent=running?'Pause':'Reprendre';}
function finish(done){running=false;active=false;completed=done;$('result').textContent=done?'Séance terminée.':'Séance arrêtée.';show('finish');}
function advance(){if(++index>=steps.length){finish(true);return;}remaining=steps[index].seconds;deadline=performance.now()+remaining*1000;last=performance.now();render();beep();}
$('start').onclick=()=>{steps=current.steps.map(s=>({...s}));index=0;remaining=steps[0].seconds;elapsed=0;started=new Date().toISOString();active=true;running=true;last=performance.now();deadline=last+remaining*1000;try{audio??=new AudioContext();audio.resume();}catch{}show('player');render();};
$('pause').onclick=()=>{if(!active)return;if(running){remaining=Math.max(0,(deadline-performance.now())/1000);running=false;}else{running=true;last=performance.now();deadline=last+remaining*1000;}render();};
$('skip').onclick=()=>{if(active)advance();};$('stop').onclick=()=>{if(active)finish(false);};
$('easy').onclick=()=>{for(let n=index;n<steps.length;n++)if(steps[n].phase==='Exercice'||steps[n].phase==='Préparation'){steps[n].cue=steps[n].easy;steps[n].target='Variante facile · À ton rythme';}render();};
setInterval(()=>{if(!active||!running)return;const now=performance.now(),gap=now-last;if(gap>5000){remaining=Math.max(0,(deadline-last)/1000);running=false;render();$('next').textContent='Séance mise en pause après une interruption. Reprends quand tu es prêt.';return;}elapsed+=gap/1000;last=now;remaining=Math.max(0,(deadline-now)/1000);if(remaining<=0)advance();else $('clock').textContent=fmt(Math.ceil(remaining));},100);
$('back').onclick=()=>{show('setup');refresh();};
$('download').onclick=()=>{const report={version:1,started,session:current.title,completed,activeSeconds:Math.round(elapsed),difficulty:$('difficulty').value,kneeDuring:$('feedback-knee').value,kneeNextMorning:null};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bilan-${started.slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('error').textContent='Le plein écran n’est pas disponible dans ce navigateur.';}};
document.addEventListener('keydown',e=>{if(!active||['SELECT','INPUT','BUTTON'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();$('pause').click();}if(e.code==='ArrowRight'){e.preventDefault();$('skip').click();}});
try{const response=await fetch('./data/program.json',{cache:'no-store'});if(!response.ok)throw Error('Programme indisponible.');data=validate(await response.json());data.days.forEach((d,i)=>{const o=document.createElement('option');o.value=i;o.textContent=d.day;$('day').append(o);});$('day').value=(new Date().getDay()+6)%7;const {values,bad}=parseSettings(location.search,data.days.map(d=>d.day));if('day' in values)$('day').value=values.day;if('minutes' in values)$('duration').value=values.minutes;if('energy' in values)$('energy').value=values.energy;if('knee' in values)$('knee').value=values.knee;if('run' in values)$('run').value=values.run;for(const id of ['day','duration','energy','knee','run'])$(id).onchange=()=>{$('error').textContent='';$('applied').textContent='';refresh();};refresh();if(Object.keys(values).length)$('applied').textContent='Réglages reçus par l’adresse : '+['day','duration','energy','knee','run'].map(id=>$(id).selectedOptions[0].textContent).join(' · ');if(bad.length){$('error').textContent=`Réglage non reconnu dans l’adresse : ${bad.join(', ')}. Corrige-le ou choisis à la main.`;$('start').disabled=true;}}catch(e){$('error').textContent=`Impossible de charger les séances : ${e.message} Lance ce site avec un serveur HTTP.`;}
